# Generated by Django 5.2 on 2025-04-21 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(help_text='City/Municipality', max_length=100)),
                ('age_group', models.CharField(choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45+', '45 and above')], max_length=5)),
                ('current_situation', models.CharField(choices=[('shs', 'Senior High School Student/Graduate'), ('college', 'College Student'), ('unemployed', 'Unemployed'), ('employed', 'Employed'), ('self_employed', 'Self-employed/business owner')], max_length=20)),
                ('freelance_experience', models.CharField(choices=[('independent', 'Yes, as an independent freelancer (with direct clients)'), ('agency', 'Yes, as part of a freelancing agency'), ('applied', 'Not yet, but I’ve created accounts and applied'), ('explored', 'I’ve explored freelancing but haven’t applied'), ('none', 'No experience at all – I’m totally new to this!')], max_length=20)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
