# Generated by Django 5.2 on 2025-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='current_situation',
        ),
        migrations.AddField(
            model_name='registration',
            name='education',
            field=models.CharField(choices=[('Senior High School Student', 'Senior High School Student'), ('College Student', 'College Student'), ('College Graduate', 'College Graduate'), ('Master’s Student / Graduate', 'Master’s Student / Graduate')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='freelance_experience',
            field=models.CharField(choices=[('independent', 'Yes, as an independent freelancer (with direct clients)'), ('agency', 'Yes, as part of a freelancing agency'), ('applied', 'Not yet, but I’ve created accounts and applied'), ('explored', 'I’ve explored freelancing but haven’t applied'), ('none', 'No experience at all – I’m totally new to this!')], max_length=100),
        ),
    ]
