# Generated by Django 5.2 on 2025-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_registration_current_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='work_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Self-employed / Business Owner', 'Self-employed / Business Owner'), ('Unemployed', 'Unemployed'), ('Freelancer', 'Freelancer'), ('Part-time Worker', 'Part-time Worker')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='freelance_experience',
            field=models.CharField(choices=[('Yes, as an independent freelancer (with direct clients)', 'Yes, as an independent freelancer (with direct clients)'), ('Yes, as part of a freelancing agency', 'Yes, as part of a freelancing agency'), ('Not yet, but I’ve created accounts and applied', 'Not yet, but I’ve created accounts and applied'), ('I’ve explored freelancing but haven’t applied', 'I’ve explored freelancing but haven’t applied'), ('No experience at all – I’m totally new to this!', 'No experience at all – I’m totally new to this!')], max_length=100),
        ),
    ]
